version: '3'
services:
  server:
    restart: always
    env_file: Premier-eye.API/.env
    image: sapfir0/web-premier-eye:server
    build:
      context: Premier-eye.API
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - "./Premier-eye.API/static/uploads:/pyfront/application/static/uploads"
      - "./data.db:/pyfront/application/data.db"
    networks:
      - some-net

  client:
    restart: always
    image: sapfir0/web-premier-eye:client
    build:
      context: Premier-eye.SPA
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    stdin_open: true

networks:
  some-net:
    driver: bridge