version: '3'
services:
  server:
    restart: always
    env_file: Premier-eye.API/.env.prod
    image: sapfir0/web-premier-eye:server
    build:
      context: Premier-eye.API
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8050 app:app
    volumes:
      - "./Premier-eye.API:/api"
    networks:
      - some-net
    ports:
      - 8050:8050

  client:
    restart: always
    image: sapfir0/web-premier-eye:client
    build:
      context: Premier-eye.SPA
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    stdin_open: true

networks:
  some-net:
    driver: bridge