version: '3'
services:
  web:
    restart: always
    env_file: Premier-eye.API/.env.prod
    image: sapfir0/web-premier-eye:server
    build:
      context: Premier-eye.API
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8050 app:app
    volumes:
      - "./Premier-eye.API:/api"
    networks:
      - some-net
    ports:
      - 8050:8050


networks:
  some-net:
    driver: bridge