version: '3'
services:
  server:
    restart: always
    env_file: application/.env
    image: sapfir0/web-premier-eye:server
    build:
      context: application
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - "./application/static/uploads:/pyfront/application/static/uploads"
      - "./data.db:/pyfront/application/data.db"
    networks:
      - some-net

  client:
    restart: always
    image: sapfir0/web-premier-eye:client
    build:
      context: SPA
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    stdin_open: true

networks:
  some-net:
    driver: bridge